
language: python
python:
  - 3.8
services:
  - postgresql
install:
  - pip install pipenv pytest flask psycopg2
  - pipenv install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - pytest test.py
