
language: python
python:
  - 3.8
services:
  - docker
  - postgresql
  - flask
install:
  - sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - pip install pipenv pytest flask psycopg2
  - pipenv install
script:
  - pytest test.py
